### ISSUE TITLE
Misspelling in ReadMe

### ISSUE THREAD

**Issue by HTMLGhozt** [LambdaSchool/Sprint-Challenge--DevOps#21]
"Given the `commend` docker run -p 49160:8080 -d <your_docker_username>/<your_docker_image_name>, what does 49160:8080 specify?"

`Commend` should be `command` on the second assessment question.

**Comment by etisdew** [comment]
I'm on it.

**Comment by ryan-hamblin** [comment]
Fixed by @etisdew and merged into master. Thanks gang!
